name: DEV_CD

on:
    push:
        branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ${{ secrets.DEV_USERNAME }}
        key: ${{ secrets.DEV_PRIVATE_KEY }}
        port: 22
        script: |
          sudo su
          cd /home/dev-apps/analytics-api
          sudo git pull origin master
          sudo git status
          sudo npm install --only=pro
          sudo npm run build
