export default class RequestData {
    private '_id': string;
    private 'requestID': string;
    private 'telNum': string;
    private 'reportStatus': number;
    private 'sentTimeReport': Date;
    private 'providerSMSID': string;
    private 'user_pid': string;
    private 'senderID': string;
    private 'smsc': string;
    private 'requestRoute': string;
    private 'campaign_name': string;
    private 'campaign_pid': string;
    private 'curRoute': string;
    private 'expiry': string;
    private 'isCopied': string;
    private 'requestDate': Date;
    private 'userCountryCode': string;
    private 'requestUserid': string;
    private 'status': string;
    private 'userCredit': string;
    private 'isSingleRequest': string;
    private 'deliveryTime': Date;
    private 'route': string;
    private 'credit': number;
    private 'oppri': number;
    private 'crcy': string;
    private 'node_id': string;

    constructor(attr: any) {
        this._id = attr['_id'].toString();
        this.requestID = attr['requestID'];
        this.telNum = attr['telNum'];
        this.reportStatus = attr['reportStatus'];
        this.sentTimeReport = attr['sentTimeReport'];
        this.providerSMSID = attr['providerSMSID'];
        this.user_pid = attr['user_pid'];
        this.senderID = attr['senderID'];
        this.smsc = attr['smsc'];
        this.requestRoute = attr['requestRoute'];
        this.campaign_name = attr['campaign_name'];
        this.campaign_pid = attr['campaign_pid'];
        this.curRoute = attr['curRoute'];
        this.expiry = attr['expiry'];
        this.isCopied = attr['isCopied'];
        this.requestDate = attr['requestDate'];
        this.userCountryCode = attr['userCountryCode'];
        this.requestUserid = attr['requestUserid'];
        this.status = attr['status'];
        this.userCredit = attr['userCredit'];
        this.isSingleRequest = attr['isSingleRequest'];
        this.deliveryTime = attr['deliveryTime'];
        this.route = attr['route'];
        this.credit = parseFloat(attr['credit']);
        this.oppri = parseFloat(attr['oppri'] || 0);
        this.crcy = attr['crcy'];
        this.node_id = attr['node_id'];
    }
}